### ISSUE TITLE
使用泛型，然后启动springboot项目的时候会由于泛型导致的NPE

### ISSUE THREAD

**Issue by fteng1024** [apache/dubbo-spi-extensions#16]
java.lang.ClassNotFoundException: T
initClassTypeWithDefaultValueNoProceeField 这个方法会报NPE.
dubbo-api-docs-core 2.7.8.1
dubbo-api-docs-annotations 2.7.8.1
咱这个不支持List<T>吗？

**Comment by fteng1024** [comment]
![image](https://user-images.githubusercontent.com/42194889/107111355-7ef9ae80-688a-11eb-9fa6-76eaa6c69fd2.png)
这样的泛型解析不了，但是
![image](https://user-images.githubusercontent.com/42194889/107111365-90db5180-688a-11eb-946b-b447df2df76b.png)
这种解析就有问题。

**Comment by KeRan213539** [comment]
不好意思给您带来困扰, 这个问题已在 2.7.8.2(还未发版)修复, 预计年后应该会发版

**Comment by fteng1024** [comment]
> 不好意思给您带来困扰, 这个问题将在 2.7.8.2修复, 预计年后应该会发版

好的，那我年后再使用最新版本的试试

**Comment by KeRan213539** [comment]
> 好的，那我年后再使用最新版本的试试

嗯嗯,感谢您的理解~

**Comment by AlbumenJ** [comment]
close #16 via #17
