### ISSUE TITLE
redis的注册中心无法指定数据库序号，与dubbo 2.x不一致

### ISSUE THREAD

**Issue by mlkt** [apache/dubbo-spi-extensions#207]
https://github.com/apache/dubbo/blob/2.6.x/dubbo-registry/dubbo-registry-redis/src/main/java/com/alibaba/dubbo/registry/redis/RedisRegistry.java#L136

dubbo 2.x可以设置db.index参数指定要使用的redis数据库序号

**Comment by AlbumenJ** [comment]
Would you please try to fix it?

**Comment by aofall** [comment]
fix by #247
