### ISSUE TITLE
仓库下不同SPI扩展的版本不统一

### ISSUE THREAD

**Issue by aofall** [apache/dubbo-spi-extensions#229]
例如 dubbo-api-docs-annotations 只有1.0.0，而 dubbo-cluster-specify-address-dubbo3 却有 1.0.2，建议像dubbo仓库那样统一版本。

```
<dependency>
    <groupId>org.apache.dubbo.extensions</groupId>
    <artifactId>dubbo-api-docs-annotations</artifactId>
    <version>1.0.0</version>
</dependency>
<dependency>
    <groupId>org.apache.dubbo.extensions</groupId>
    <artifactId>dubbo-cluster-specify-address-dubbo3</artifactId>
    <version>1.0.2</version>
</dependency>
```

另外还有一个问题，各个不同的子模块引用了dubbo3不同版本的依赖，有dubbo3.1的，也有dubbo3.2的，这个也需要统一，目前测试如果全局升级到 dubbo 3.2 部分模块需要同步改造 3.2 的写法

**Comment by AlbumenJ** [comment]
这一块需要一个统一的设计，因为部分组件可能会长期不动兼容所有版本

**Comment by songxiaosheng** [comment]
@aofall 感兴趣不 一起完善下 目前计划的是大版本与主仓库保持一致，统一打包，小版本各自更新
https://github.com/apache/dubbo-spi-extensions/issues/232

**Comment by aofall** [comment]
> @aofall 感兴趣不 一起完善下 目前计划的是大版本与主仓库保持一致，统一打包，小版本各自更新 #232

可以的，关于版本的具体规划是怎么样呢？比如 `3.2.7.1` 这样子吗？然后创建诸如 `3.2.0.1` `3.2.7.1` 等多个分支这样子吗？

前段时间我尝试统一dubbo版本，发现各个小版本之间也有方法差异，如 dubbo3.2.0 中的 `org.apache.dubbo.rpc.protocol.dubbo.ByteAccessor` 只有 `getRpcInvocation` 一个方法，而 dubbo3.2.7 中有 `getRpcInvocation` 和 `getRpcResult` 两个方法，如果只像 dubbo 仓库那样分只细分到 `3.1` `3.2` `3.3` 分支的话，可能无法兼容所有的版本

**Comment by songxiaosheng** [comment]
精确到第二个应该可以兼容大部分场景了吧

**Comment by aofall** [comment]
等 #231 这个小功能合并后就可以创建相关分支开始规划的内容了

**Comment by songxiaosheng** [comment]
> 等 #231 这个小功能合并后就可以创建相关分支开始规划的内容了
我瞅瞅
