### ISSUE TITLE
【3.2】 使用Protobuf做序列化器时，在INJVM模式会因为深度拷贝导致response字段为空

### ISSUE THREAD

**Issue by vio-lin** [apache/dubbo-spi-extensions#267]
## What is the purpose of the change

修复INJVM模式下 Protobuf对象，不能被正常深度拷贝

## Brief changelog

dubbo-spi-extensions\dubbo-serialization-extensions\dubbo-serialization-protobuf\src\test\java\org\apache\dubbo\common\serialize\protobuf\support\ProtobufParamDeepCopyUtilTest.java

dubbo-spi-extensions\dubbo-serialization-extensions\dubbo-serialization-protobuf\src\main\resources\META-INF\dubbo\internal\org.apache.dubbo.rpc.protocol.injvm.ParamDeepCopyUtil

## Verifying this change

增加一个wraper 扩展，假如继承protobuf的接口，则使用另外的序列化器。  

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before
  you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address
  just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit
  in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency
  exist. If the new feature or significant change is committed, please remember to add sample
  in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure
  unit-test and integration-test pass.
- [x] If this contribution is large, please follow
  the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

**Comment by songxiaosheng** [comment]
Can you help fix this problem?

**Comment by aofall** [comment]
may be fixed in #268

**Comment by Alleninggx** [comment]
https://github.com/apache/dubbo/issues/12377
