### ISSUE TITLE
[Task] Sort out the Dubbo extension library ecology and use graphics to represent it

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo-spi-extensions#302]

**Comment by songxiaosheng** [comment]
![image](https://github.com/apache/dubbo-spi-extensions/assets/81170548/1d6b387b-a215-42a2-837f-38debd9a1957)

**Comment by wcy666103** [comment]
hello,I want try this

**Comment by songxiaosheng** [comment]
> hello,I want try this

done

**Comment by wcy666103** [comment]
I sorted out the modules that dubbo and extensions have respectively, and the modules that will be extended in the future are as follows:
![image](https://github.com/apache/dubbo-spi-extensions/assets/56506697/6af0c71f-c027-4bb3-9f5c-11bda69a65e1)

Is there anything else that needs to be modified？
