### ISSUE TITLE
2.7.8.3版本下，从dubboAdmin加载api接口会报错，切换到2.7.8.2版本下没问题

### ISSUE THREAD

**Issue by cjwcjwcjwcjw** [apache/dubbo-spi-extensions#35]
- [ ] I have searched the [issues](https://github.com/apache/dubbo-spi-extensions/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/dubbo-spi-extensions/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: xxx
* Java version: jdk1.8
* Module name: dubbo-api-docs

### Steps to reproduce this issue

1. 本地启动提供者工程，在dubboAdmin输入了ip和port，提供者的后台报错：
![QQ截图20210702153448](https://user-images.githubusercontent.com/9546251/124242608-7d899500-db4f-11eb-9b7f-b36a3aa26574.png)

debug发现是这个地方缺少了IdubboDocProvider的key，在2.7.8.2版本是存在的
![image](https://user-images.githubusercontent.com/9546251/124236671-444e2680-db49-11eb-9024-56eb4bdd210e.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

期望：本版本可以兼容，顺利得到api接口文档返回

**Comment by KeRan213539** [comment]
The latest dubbo-admin code has solved this problem. Please update the dubbo-admin code to the latest (develop Branch)
