### ISSUE TITLE
加了ApiDoc注解就報錯 不加啥問題沒有

### ISSUE THREAD

**Issue by Yanghongkang** [apache/dubbo-spi-extensions#7]
加了ApiDoc注解
就報返回的對象强轉報錯
返回對象就一個汎型啊

java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

**Comment by Yanghongkang** [comment]
![image](https://user-images.githubusercontent.com/17022018/105602437-52489000-5dd0-11eb-89f7-3a688abcaea3.png)
![image](https://user-images.githubusercontent.com/17022018/105602852-6db39b00-5dd0-11eb-8d9e-33331957ac69.png)

**Comment by KeRan213539** [comment]
返回对象有泛型,但是实际使用的时候没有添加泛型, 是这样吗?
例如返回对象的定义类似 
```
public class ResponseResult<T> ... 
```
而使用的地方没有传泛型,而直接使用了 ResponseResult
这样的情况下出现的异常?

**Comment by butterflyjzf** [comment]
> 返回对象有泛型,但是实际使用的时候没有添加泛型, 是这样吗?
> 例如返回对象的定义类似
> 
> ```
> public class ResponseResult<T> ... 
> ```
> 
> 而使用的地方没有传泛型,而直接使用了 ResponseResult
> 这样的情况下出现的异常?

我在使用的时候也遇到该问题，debug发现是因为使用了BigDecimal，就会出现该异常，在ClassTypeUtil里增加BigDecimal的处理就可以了~

**Comment by KeRan213539** [comment]
> > 返回对象有泛型,但是实际使用的时候没有添加泛型, 是这样吗?
> > 例如返回对象的定义类似
> > ```
> > public class ResponseResult<T> ... 
> > ```
> > 
> > 
> > 而使用的地方没有传泛型,而直接使用了 ResponseResult
> > 这样的情况下出现的异常?
> 
> 我在使用的时候也遇到该问题，debug发现是因为使用了BigDecimal，就会出现该异常，在ClassTypeUtil里增加BigDecimal的处理就可以了~

好的,感谢反馈~

**Comment by KeRan213539** [comment]
最近做了一些修复，方便的话，请使用2.7.x分支最新代码看看还有没有这个问题，或者提供更多信息？

**Comment by Yanghongkang** [comment]
dubboservice 加上gourp和version
报 may be version or group mismatch&nbsp;


我app版本是0.0.1
org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0&nbsp;
这样子也有冲去？




Some exceptions have occurred, please check the log.org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: $invoke, provider: dubbo://10.68.6.91:20881/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider?application=dubbo-admin-api-docs&amp;generic=true&amp;interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider&amp;pid=13171&amp;register.ip=10.68.6.91&amp;remote.application=&amp;retries=0&amp;side=consumer&amp;sticky=false&amp;timeout=1000, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:20881 in [b2t-nonflight/com.ceair.b2t.nonflight.service.order.PassangerService:0.0.1:20881, b2t-nonflight/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.order.OrderService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.OrgService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.UserService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.coupon.QcCodeService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.AgentService:0.0.1:20881], may be version or group mismatch , channel: consumer: /10.68.6.91:59722 --&gt; provider: /10.68.6.91:20881, message:RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[apiModuleList, [Ljava.lang.String;@112388c2, [Ljava.lang.Object;@1fe46496], attachments={input=387, path=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, remote.application=dubbo-admin-api-docs, dubbo=2.0.2, interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0, generic=true}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:20881 in [b2t-nonflight/com.ceair.b2t.nonflight.service.order.PassangerService:0.0.1:20881, b2t-nonflight/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.order.OrderService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.OrgService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.UserService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.coupon.QcCodeService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.AgentService:0.0.1:20881], may be version or group mismatch , channel: consumer: /10.68.6.91:59722 --&gt; provider: /10.68.6.91:20881, message:RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[apiModuleList, [Ljava.lang.String;@112388c2, [Ljava.lang.Object;@1fe46496], attachments={input=387, path=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, remote.application=dubbo-admin-api-docs, dubbo=2.0.2, interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0, generic=true}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:265)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:120)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo-spi-extensions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月31日(星期天) 凌晨5:25
收件人:&nbsp;"apache/dubbo-spi-extensions"<dubbo-spi-extensions@noreply.github.com&gt;;
抄送:&nbsp;"附近人A9B5D1936EA904F63"<691557741@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/dubbo-spi-extensions] 加了ApiDoc注解就報錯 不加啥問題沒有 (#7)





 
最近做了一些修复，方便的话，请使用2.7.x分支最新代码看看还有没有这个问题，或者提供更多信息？

**Comment by KeRan213539** [comment]
> dubboservice 加上gourp和version
> 
> 报 may be version or group mismatch&nbsp;
> 
> 
> 
> 
> 
> 我app版本是0.0.1
> 
> org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0&nbsp;
> 
> 这样子也有冲去？
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Some exceptions have occurred, please check the log.org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: $invoke, provider: dubbo://10.68.6.91:20881/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider?application=dubbo-admin-api-docs&amp;generic=true&amp;interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider&amp;pid=13171&amp;register.ip=10.68.6.91&amp;remote.application=&amp;retries=0&amp;side=consumer&amp;sticky=false&amp;timeout=1000, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:20881 in [b2t-nonflight/com.ceair.b2t.nonflight.service.order.PassangerService:0.0.1:20881, b2t-nonflight/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.order.OrderService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.OrgService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.UserService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.coupon.QcCodeService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.AgentService:0.0.1:20881], may be version or group mismatch , channel: consumer: /10.68.6.91:59722 --&gt; provider: /10.68.6.91:20881, message:RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[apiModuleList, [Ljava.lang.String;@112388c2, [Ljava.lang.Object;@1fe46496], attachments={input=387, path=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, remote.application=dubbo-admin-api-docs, dubbo=2.0.2, interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0, generic=true}]
> 
> org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:20881 in [b2t-nonflight/com.ceair.b2t.nonflight.service.order.PassangerService:0.0.1:20881, b2t-nonflight/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.order.OrderService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.OrgService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.UserService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.coupon.QcCodeService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.AgentService:0.0.1:20881], may be version or group mismatch , channel: consumer: /10.68.6.91:59722 --&gt; provider: /10.68.6.91:20881, message:RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[apiModuleList, [Ljava.lang.String;@112388c2, [Ljava.lang.Object;@1fe46496], attachments={input=387, path=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, remote.application=dubbo-admin-api-docs, dubbo=2.0.2, interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0, generic=true}]
> 
> 	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:265)
> 
> 	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:120)
> 
> 	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
> 
> 	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
> 
> 	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
> 
> 	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
> 
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "apache/dubbo-spi-extensions"                                                                                    <notifications@github.com&gt;;
> 
> 发送时间:&nbsp;2021年1月31日(星期天) 凌晨5:25
> 
> 收件人:&nbsp;"apache/dubbo-spi-extensions"<dubbo-spi-extensions@noreply.github.com&gt;;
> 
> 抄送:&nbsp;"附近人A9B5D1936EA904F63"<691557741@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
> 
> 主题:&nbsp;Re: [apache/dubbo-spi-extensions] 加了ApiDoc注解就報錯 不加啥問題沒有 (#7)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 最近做了一些修复，方便的话，请使用2.7.x分支最新代码看看还有没有这个问题，或者提供更多信息？
> 
>  
> 
> —
> 
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.

看样子是docs的服务没注册上，能提供下您的具体配置吗？注册中心是什么？dubbo版本，spring版本是什么？

**Comment by Yanghongkang** [comment]
springboot&nbsp;2.1.12.RELEASE
<dependency&gt;
    <groupId&gt;org.apache.zookeeper</groupId&gt;
    <artifactId&gt;zookeeper</artifactId&gt;
    <version&gt;3.4.7</version&gt;
</dependency&gt;
<dependency&gt;
    <groupId&gt;org.apache.dubbo</groupId&gt;
    <artifactId&gt;dubbo-spring-boot-starter</artifactId&gt;
    <version&gt;2.7.8</version&gt;
</dependency&gt;
<dependency&gt;
    <groupId&gt;org.apache.dubbo</groupId&gt;
    <artifactId&gt;dubbo-registry-zookeeper</artifactId&gt;
    <version&gt;2.7.8</version&gt;
</dependency&gt;
<dependency&gt;
    <groupId&gt;org.apache.curator</groupId&gt;
    <artifactId&gt;curator-recipes</artifactId&gt;
    <version&gt;4.1.0</version&gt;
</dependency&gt;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo-spi-extensions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 中午1:24
收件人:&nbsp;"apache/dubbo-spi-extensions"<dubbo-spi-extensions@noreply.github.com&gt;;
抄送:&nbsp;"附近人A9B5D1936EA904F63"<691557741@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/dubbo-spi-extensions] 加了ApiDoc注解就報錯 不加啥問題沒有 (#7)





  
dubboservice 加上gourp和version
 
报 may be version or group mismatch&nbsp;
 
我app版本是0.0.1
 
org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0&nbsp;
 
这样子也有冲去？
 
Some exceptions have occurred, please check the log.org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: $invoke, provider: dubbo://10.68.6.91:20881/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider?application=dubbo-admin-api-docs&amp;generic=true&amp;interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider&amp;pid=13171&amp;register.ip=10.68.6.91&amp;remote.application=&amp;retries=0&amp;side=consumer&amp;sticky=false&amp;timeout=1000, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:20881 in [b2t-nonflight/com.ceair.b2t.nonflight.service.order.PassangerService:0.0.1:20881, b2t-nonflight/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.order.OrderService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.OrgService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.UserService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.coupon.QcCodeService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.AgentService:0.0.1:20881], may be version or group mismatch , channel: consumer: /10.68.6.91:59722 --&gt; provider: /10.68.6.91:20881, message:RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[apiModuleList, [Ljava.lang.String;@112388c2, [Ljava.lang.Object;@1fe46496], attachments={input=387, path=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, remote.application=dubbo-admin-api-docs, dubbo=2.0.2, interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0, generic=true}]
 
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:20881 in [b2t-nonflight/com.ceair.b2t.nonflight.service.order.PassangerService:0.0.1:20881, b2t-nonflight/org.apache.dubbo.apidocs.core.providers.IDubboDocProvider:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.order.OrderService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.OrgService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.UserService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.coupon.QcCodeService:0.0.1:20881, b2t-nonflight/com.ceair.b2t.nonflight.service.org.AgentService:0.0.1:20881], may be version or group mismatch , channel: consumer: /10.68.6.91:59722 --&gt; provider: /10.68.6.91:20881, message:RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[apiModuleList, [Ljava.lang.String;@112388c2, [Ljava.lang.Object;@1fe46496], attachments={input=387, path=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, remote.application=dubbo-admin-api-docs, dubbo=2.0.2, interface=org.apache.dubbo.apidocs.core.providers.IDubboDocProvider, version=0.0.0, generic=true}]
 
at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:265)
 
at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:120)
 
at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
 
at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
 
at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
 
at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 
at java.lang.Thread.run(Thread.java:748)
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "apache/dubbo-spi-extensions"                                                                                    <notifications@github.com&gt;;
 
发送时间:&nbsp;2021年1月31日(星期天) 凌晨5:25
 
收件人:&nbsp;"apache/dubbo-spi-extensions"<dubbo-spi-extensions@noreply.github.com&gt;;
 
抄送:&nbsp;"附近人A9B5D1936EA904F63"<691557741@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 
主题:&nbsp;Re: [apache/dubbo-spi-extensions] 加了ApiDoc注解就報錯 不加啥問題沒有 (#7)
 
最近做了一些修复，方便的话，请使用2.7.x分支最新代码看看还有没有这个问题，或者提供更多信息？
 
—
 
You are receiving this because you authored the thread.
 
Reply to this email directly, view it on GitHub, or unsubscribe.
  
看样子是docs的服务没注册上，能提供下您的具体配置吗？注册中心是什么？dubbo版本，spring版本是什么？

**Comment by KeRan213539** [comment]
@Yanghongkang 您好,我这边暂时无法复现您的问题, 我们将要发布 2.7.8.2 版本,请您到时候再用这个版本试试? 或者可以用 2.7.x 分支的最新代码试试?

**Comment by fteng1024** [comment]
@KeRan213539 
你好，我这边也出现了这样的问题，我在实现类里面指定了具体的对象，但是反射的时候好像并没有拿到我这边指定的具体类型

**Comment by KeRan213539** [comment]
> @KeRan213539 
> 
> 你好，我这边也出现了这样的问题，我在实现类里面指定了具体的对象，但是反射的时候好像并没有拿到我这边指定的具体类型

近期做了一波修复，等2.7.8.2发版了再试试？年后应该可以发版

**Comment by KeRan213539** [comment]
Sorry, because you didn't reply for a long time, we will close this PR first.
Please feel free to reopen it if you have any question.
