### ISSUE TITLE
Support for internal subclasses

### ISSUE THREAD

**Issue by ChinaJeckXu** [apache/dubbo-spi-extensions#8]
:ambulance: Currently, internal classes are not supported, and I hope the official support.

**Comment by KeRan213539** [comment]
Can you provide a more detailed description?

**Comment by ChinaJeckXu** [comment]
> Can you provide a more detailed description?

In complex business systems, certain sub-categories and internal category models usually appear, and we hope that dubbo-api-docs of the 2.7.X branch can support them.

**Comment by KeRan213539** [comment]
PR in #9 solves this problem

**Comment by KeRan213539** [comment]
We will solve this problem as soon as possible

**Comment by AlbumenJ** [comment]
close #8 via #13
