### ISSUE TITLE
How can I get peakEwmaLoadBalance from maven  center repo?

### ISSUE THREAD

**Issue by 24kpure** [apache/dubbo-spi-extensions#88]
I'd like  to make easily access to  peakEwmaLoadBalance.

**Comment by 24kpure** [comment]
HELP!

**Comment by 24kpure** [comment]
HELP AGAIN !

**Comment by haoyann** [comment]
Wait for the next release.

**Comment by 24kpure** [comment]
> Wait for the next release.

Thank you very much.By the way ,what's the date of next release?
